kind: Route
metadata:
  labels:
    app: todonodejs
    name: frontend
  name: frontend
spec:
  hosts: todo.apps.ocp4.example.com
  path: "/todo"
  to:
    kind: Service
    name: frontend-apac
    weight: 100
  wildcardPolicy: None
